{% set name = "kalasiris" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: aadb874074caaf39ba4900d2d1f0f5722fd5c7bb4b1c7dcf17cfdf79b800f1e0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  source_files:
    - tests/test_kalasiris.py
    - tests/utils.py

about:
  home: http://github.com/rbeyer/kalasiris
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python library to wrap functions and functionality for the Integrated Software for Imagers and Spectrometers (ISIS).
  description: |
    The kalasiris library wraps functions and functionality for the 
    Integrated Software for Imagers and Spectrometers (ISIS)
    <https://isis.astrogeology.usgs.gov>.  
    Primarily a very lightweight wrapper around Python's subprocess
    module to allow easy calling of ISIS programs in the shell from 
    within Python.  Works with ISIS 3.6.0+, probably works with 
    ISIS 3+. Works with Python 3.6.0+.  It is pure Python code with
    no Python dependencies, but is useless if you don't have ISIS
    installed on your system (and will error on import).
  doc_url: http://kalasiris.readthedocs.io/
  dev_url: https://github.com/rbeyer/kalasiris

extra:
  recipe-maintainers:
    - rbeyer
